"""empty message

Revision ID: 2c69775c7358
Revises: 
Create Date: 2024-11-26 21:11:28.527342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c69775c7358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('league', 'playoff', name='tournament_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', 'canceled', name='tournament_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoreHome', sa.Integer(), nullable=True),
    sa.Column('scoreAway', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'ended', name='match_status_enum'), nullable=False),
    sa.Column('homeTeam_id', sa.Integer(), nullable=False),
    sa.Column('awayTeam_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['awayTeam_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['homeTeam_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('substitute', 'field', name='player_position_enum'), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='player_status_enum'), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventType', sa.Enum('goal', 'redCard', name='matchEvent_type_enum'), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_event')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_table('coach')
    op.drop_table('team')
    op.drop_table('tournament')
    # ### end Alembic commands ###
